### ISSUE TITLE
Update to App Bridge 2

### ISSUE THREAD

**Issue by asecondwill** [Shopify/turbolinks-jwt-sample-app#41]
This is a requirement now to pass the app review.

**Comment by tdonia** [comment]
can you share what local changes you've made to the app?  i've just tried bumping the `shopify_app` gem in a clean clone, and it seems to work without issue. here's the branch: https://github.com/Shopify/turbolinks-jwt-sample-app/compare/shopify_app-18-update

**Comment by oliwoodsuk** [comment]
Do you have this line of code in your theme: `<script src="https://unpkg.com/@shopify/app-bridge@1"></script>` ?
If so, I think you'll have to bump it up to @2

**Comment by tdonia** [comment]
my branch uses the unversioned/latest unpkg link unchanged from the main branch: https://github.com/Shopify/turbolinks-jwt-sample-app/blob/shopify_app-18-update/app/views/layouts/embedded_app.html.erb#L27 which resolves to `2.0.3` and seems to work for me without issue?

**Comment by netwire88** [comment]
Should we continue to use 

```
  window.app = createApp({
    apiKey: data.apiKey,
    shopOrigin: data.shopOrigin,
  });
```
in [shopify_app.js](https://github.com/Shopify/turbolinks-jwt-sample-app/blob/master/app/javascript/shopify_app/shopify_app.js)? It seems like that's working instead of `host`.

**Comment by kirillplatonov** [comment]
Here's an example app with JWT integration and AppBridge 2: https://github.com/kirillplatonov/shopify-hotwire-sample

**Comment by tdonia** [comment]
@netwire88 -- sorry for the delay. `host` should be used instead of `shopOrigin` -- as in @kirillplatonov's [example](https://github.com/kirillplatonov/shopify-hotwire-sample/blob/main/app/javascript/shopify_app/shopify_app.js#L13) or in the updated [shopify_app.js](https://github.com/Shopify/turbolinks-jwt-sample-app/blob/master/app/javascript/shopify_app/shopify_app.js#L23) example in this repo.  now that #45 has been merged I'm going to close this issue.

**Comment by kirillplatonov** [comment]
@tdonia can we also merge App Bridge 2 related PR in shopify_app gem?
https://github.com/Shopify/shopify_app/pull/1277

And once it merge I could also open PR with this change: https://github.com/kirillplatonov/shopify_app/commit/b46ccc1d3607ae0e7aee210c0e79c8ef70866b26
