### ISSUE TITLE
Shopify gives me the same session token

### ISSUE THREAD

**Issue by martyboggs** [Shopify/turbolinks-jwt-sample-app#9]
I tried this code from the readme, but I'm getting the same token. Since Shopify is caching the token, I had to change 50000 to 60000. There's still a small chance the token will be expired.

```
async function retrieveToken(app) {
  window.sessionToken = await getSessionToken(app);
}

function keepRetrievingToken(app) {
  setInterval(() => {
    retrieveToken(app);
  }, 50000);
}
```

**Comment by forsbergplustwo** [comment]
Firstly, thank you for providing this repo, it's been a great help!

I'm seeing the same thing as @martyboggs when using the code from `/app/javascript/shopify_app/shopify_app.js``

In my Rails logs I see the following, when the setInterval timer is 50000.

```
21:16:56 web.1     | [ShopifyApp::JWT] Failed to validate JWT: [JWT::ExpiredSignature] Signature has expired
21:16:56 web.1     | Started GET "/products" for 127.0.0.1 at 2020-10-20 21:16:56 +0200
21:16:56 web.1     | Processing by ProductsController#index as HTML
21:16:56 web.1     |   Shop Load (0.2ms)  SELECT "shops".* FROM "shops" WHERE "shops"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
21:16:56 web.1     | [ShopifyApp::Itp] Clearing top level oauth cookie...
21:16:56 web.1     | [ShopifyApp::LoginProtection] Activating session...
21:16:57 web.1     |   Rendering app/views/products/index.html.erb within layouts/embedded_app
21:16:57 web.1     |   Rendered app/views/products/index.html.erb within layouts/embedded_app (Duration: 0.5ms | Allocations: 334)
21:16:57 web.1     |   Rendered app/views/layouts/_flash_messages.html.erb (Duration: 0.1ms | Allocations: 88)
21:16:57 web.1     | [ShopifyApp::LoginProtection] Clearing session...
21:16:57 web.1     | Completed 200 OK in 362ms (Views: 5.1ms | ActiveRecord: 0.2ms | Allocations: 11551)
```

Strangely, after I set it to 55000 for the interval I'm no longer seeing this in the logs. But I'm unsure as to why it was set to 50000 to begin with, and why adjusting it changes the behavoir.

Also, if the JWT validation failed, should it not error out in some way or redirect me to the splash_page again? It continued on processing the request without issue.

Many thanks!

**Comment by ko-lem** [comment]
I also had the same issue. Changing the interval from 50000 to 60000 also solved it for me.

**Comment by NabeelAhsen** [comment]
Thank you for bringing this to our attention!

Accounting for average round-trip network latency,  CPU usage on most browsers, and caching, our new recommended **refresh interval is to request a new session token every 2 seconds**. This minimizes the chance that any session token given to your app is close to expiry. The reason this is "good enough" is because Shopify Admin caches tokens for a period of time, making it cheap to request them from App Bridge.

We have updated our [public guide](https://shopify.dev/tutorials/authenticate-server-side-rendered-apps-with-session-tokens-app-bridge-turbolinks#fetch-and-store-session-tokens) to recommend an interval of 2 seconds as well.

**Aside:**

We realize that polling for tokens on your app is less than ideal; we're still exploring ways for multi-page apps to not need to do this in the first place.

**Comment by igravious** [comment]
> We realize that polling for tokens on your app is less than ideal; we're still exploring ways for multi-page apps to not need to do this in the first place.
@NabeelAhsen Oh, you mean like every non-SPA Rails app ever. For a company that does so much with RoR it's a pain that you don't support the traditional way of working with RoR with your Vanilla docs. It's maddening that you funnel us towards using React and GraphQL. I've been banging my head against `[ShopifyApp::JWT] Failed to validate JWT: [JWT::ExpiredSignature] Signature has expired` in RoR because the _correct_ way is not to use RoR apparently.

**Comment by bilfeldt** [comment]
Dear @NabeelAhsen

> We have updated our [public guide](https://shopify.dev/tutorials/authenticate-server-side-rendered-apps-with-session-tokens-app-bridge-turbolinks#fetch-and-store-session-tokens) to recommend an interval of 2 seconds as well.

The link above is for a no-longer existing section and the page does not mention a recommended pulling time (only the 60 sec lifetime). Is 2 sec still the recommended pulling time for new session tokens?
